In [4]:
using Images
using ProgressMeter
using Statistics
using LinearAlgebra
using Plots

┌ Info: Recompiling stale cache file /Users/edwardli/.julia/compiled/v1.2/Images/H8Vxc.ji for Images [916415d5-f1e6-5110-898d-aaa5f9f070e0]
└ @ Base loading.jl:1240
┌ Info: Precompiling ProgressMeter [92933f4c-e287-5a05-a399-4b506db050ca]
└ @ Base loading.jl:1242
┌ Info: Recompiling stale cache file /Users/edwardli/.julia/compiled/v1.2/Plots/ld3vC.ji for Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
└ @ Base loading.jl:1240


In [5]:
SPEC_DIR = "spectrograms"
GENRES = ["classical", "edm", "rock"]

3-element Array{String,1}:
 "classical"
 "edm"      
 "rock"     

In [6]:
A = zeros(367, 288)

367×288 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.

In [25]:
counter = 1

for genre in GENRES
    println(genre)
    for (root, dir, files) in walkdir(joinpath(SPEC_DIR, genre))
        @showprogress for image in files
            if !occursin(".png", image) continue end
            if occursin("checkpoint", image) continue end
            
            im = channelview(Gray.(load(joinpath(SPEC_DIR, genre, image))))
            ra = [mean(im[i, :]) for i = 1:size(im)[1]]
            A[counter, :] = ra'
            global counter
            counter += 1
        end
    end
end

classical


Progress: 100%|█████████████████████████████████████████| Time: 0:00:00


edm


Progress: 100%|█████████████████████████████████████████| Time: 0:00:01


rock


Progress: 100%|█████████████████████████████████████████| Time: 0:00:00


In [26]:
A_centered = [A[i, j] - mean(A[:, j]) for i=1:size(A)[1], j=1:size(A)[2]]

367×288 Array{Float64,2}:
 -0.100749    -0.100749    -0.100749    …   0.00590338   0.00590338
 -0.102982    -0.102982    -0.102982       -0.202212    -0.202212  
 -0.0808596   -0.0808596   -0.0808596      -0.100115    -0.100115  
 -0.0650463   -0.0650463   -0.0650463      -0.197982    -0.197982  
 -0.0996232   -0.0996232   -0.0996232      -0.0625607   -0.0625607 
 -0.08745     -0.08745     -0.08745     …  -0.129627    -0.129627  
 -0.102764    -0.102764    -0.102764       -0.18973     -0.18973   
 -0.098779    -0.098779    -0.098779       -0.107386    -0.107386  
 -0.101784    -0.101784    -0.101784       -0.122737    -0.122737  
 -0.102219    -0.102219    -0.102219       -0.361508    -0.361508  
 -0.100513    -0.100513    -0.100513    …  -0.170549    -0.170549  
 -0.0783814   -0.0783814   -0.0783814      -0.203174    -0.203174  
 -0.0777278   -0.0777278   -0.0777278      -0.0531743   -0.0531743 
  ⋮                                     ⋱                          
  0.0592184    0.05921

In [27]:
ColLength = [sqrt(sum(A_centered[i, j]^2 for i=1:size(A)[1])) for j=1:size(A)[2]]

288-element Array{Float64,1}:
 1.3630272613664094
 1.3630272613664094
 1.3630272613664094
 2.173582161547399 
 2.173582161547399 
 2.444972788274052 
 2.444972788274052 
 2.51097417508183  
 2.51097417508183  
 2.520274852074242 
 2.520274852074242 
 2.520274852074242 
 2.530216704462127 
 ⋮                 
 1.6463783981693414
 1.715825051758548 
 1.715825051758548 
 1.7248177231220216
 1.7248177231220216
 1.7248177231220216
 1.9639337439571094
 1.9639337439571094
 2.548006712969892 
 2.548006712969892 
 2.1372626507176378
 2.1372626507176378

In [28]:
B = [A_centered[i, j] / ColLength[j] for i=1:size(A)[1], j=1:size(A)[2]]

367×288 Array{Float64,2}:
 -0.0739155   -0.0739155   -0.0739155   …   0.00276212   0.00276212
 -0.0755539   -0.0755539   -0.0755539      -0.0946127   -0.0946127 
 -0.0593236   -0.0593236   -0.0593236      -0.0468427   -0.0468427 
 -0.0477219   -0.0477219   -0.0477219      -0.0926334   -0.0926334 
 -0.0730897   -0.0730897   -0.0730897      -0.0292714   -0.0292714 
 -0.0641587   -0.0641587   -0.0641587   …  -0.0606508   -0.0606508 
 -0.075394    -0.075394    -0.075394       -0.0887725   -0.0887725 
 -0.0724703   -0.0724703   -0.0724703      -0.0502448   -0.0502448 
 -0.0746748   -0.0746748   -0.0746748      -0.0574271   -0.0574271 
 -0.0749944   -0.0749944   -0.0749944      -0.169145    -0.169145  
 -0.0737424   -0.0737424   -0.0737424   …  -0.0797979   -0.0797979 
 -0.0575054   -0.0575054   -0.0575054      -0.0950629   -0.0950629 
 -0.0570259   -0.0570259   -0.0570259      -0.0248796   -0.0248796 
  ⋮                                     ⋱                          
  0.0434463    0.04344

In [29]:
U, sigma, V = svd(B, full=true)

SVD{Float64,Float64,Array{Float64,2}}([-0.05152592979354509 0.010950767032612219 … -0.011921311414853789 -0.005559645520363514; -0.10125851343601366 0.13273999352144755 … 0.031374260835352344 -0.034998530630195694; … ; -0.010938222089207618 0.016135847086522565 … 0.06463999278148834 -0.012443102216493465; 0.028612068231210975 0.003244830419389214 … -0.007479018780001385 0.041421645195630026], [15.082059422023365, 4.368098939012903, 2.9929931457229575, 2.2820400683941457, 1.9657370321860659, 1.9164710907814144, 1.5468006966691241, 1.4736788304218071, 1.409870199947708, 1.1740532888760766  …  1.321404682747715e-15, 1.321404682747715e-15, 1.321404682747715e-15, 1.321404682747715e-15, 1.321404682747715e-15, 1.321404682747715e-15, 1.321404682747715e-15, 1.321404682747715e-15, 1.321404682747715e-15, 1.321404682747715e-15], [0.05797521169529004 0.05797521169528996 … 0.04048836020371804 0.04048836020371806; -0.060789478872804864 -0.06078947887280517 … -0.035344346982219485 -0.03534434698221954

In [30]:
y1 = B * V[:, 1]
y2 = B * V[:, 2]
y3 = B * V[:, 3]

367-element Array{Float64,1}:
 -0.15068702206654616 
  0.014627199786815655
  0.0365937657261286  
 -0.2791116882061703  
 -0.18721025228439603 
 -0.08809988824695511 
 -0.4116133004789611  
  0.2654851031199799  
 -0.24097332845440456 
 -0.061335435340798536
 -0.08188614670081143 
 -0.04407049789763792 
  0.00893812744037049 
  ⋮                   
 -0.14857511341875299 
  0.0560874939413394  
  0.18320366239363878 
  0.13846651889311665 
  0.17320386261921705 
 -0.03538042217464572 
 -0.11013473729328743 
 -0.01693832027275664 
  0.10954133475111649 
 -0.1446255497881851  
  0.3087612506640677  
  0.21516214493393304 

In [ ]:
plot(V[:, 1])

In [ ]:
scatter(y1[1:103], y2[1:103])
scatter!(y1[104:104+216-1], y2[104:104+216-1])
scatter!(y1[104+216:size(y1)[1]], y2[104+216:size(y2)[1]])

In [ ]:
scatter(y1[1:103], y2[1:103], y3[1:103], aspect_ratio=:equal)
scatter!(y1[104:104+216-1], y2[104:104+216-1], y3[104:104+216-1])
scatter!(y1[104+216:size(y1)[1]], y2[104+216:size(y2)[1]], y3[104+216:size(y2)[1]])